### ISSUE TITLE
Some feedback from a quick readthrough

### ISSUE THREAD

**Issue by mikegraham** [mrocklin/dask-binder#1]
array.ipynb

 - The description at the top "Dask Dataframes coordinate many Pandas dataframes," applies to dataframe, not array.

 - If this notebook is intended as one of the main intros, it's sort of annoying that the dashboard link situation is so fussy--I first clicked without running the cell, then ran the cell and got a link that won't work, then could click the right link. Since the link isn't going to be right, it might be less noise not to present the (cool) HTML repr of the client.

 - "This creates a 10000, 10000 arrays of random number" -> "This creates a 10000, 10000 array of random number"

 - "This creates a 10000, 10000 arrays of random numbers, split into a 10x10 grid of 1000x1000 NumPy arrays."  I know you probably want to avoid verbosity, but as this is one of the fundamental dask-unique concepts it might be nice to answer some basic questions about how chunks work, e.g. "This creates a 10000x10000 array of random numbers, represented as many numpy arrays of size 1000x1000 (or smaller if the array cannot be divided evenly). In this case there are 100 (10x10) numpy arrays of size 1000x1000."

dataframe.ipynb

 - compute is used but not explained like it was in the array notebook

 - The mix of eager operations and lazy operations is significant, and I don't know if someone would walk away having a real sense for what operations would do what.

 - The warning ```/srv/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: `meta` is not specified, inferred from partial data. Please provide `meta` if the result is unexpected.
  Before: .apply(func)
  After:  .apply(func, meta={'x': 'f8', 'y': 'f8'}) for dataframe result
  or:     .apply(func, meta=('x', 'f8'))            for series result
  """Entry point for launching an IPython kernel.``` in the last cell is a but hard to work your way through.  (There was also a warning in cell 9, but it's a lot more digestible).

delayed.ipynb

 - `from random import random` within each function isn't a very normal pattern in Python in general, and I got hung up on why you would do it for a moment. I still don't know whether it was meaningful (like, hoping the random state would get initialized differently in each process) or just because the need was internal.

 - `zs = dask.persist(*zs)` is unexplained and can look a bit scary.

 - "Note the red bars for inter-worker communication. Also note how there is lots of parallelism at the beginning but less towards the end as we reach the top of the tree where there is less work to do." This seems to lack the part where it originally told me to look somewhere before I computed.

**Comment by mrocklin** [comment]
Thanks @mikegraham !  This is super-helpful.  I think I've addressed *most* of our suggestions in 800be7eb59b23f8de4c6714d18ffd902c3d0363c .  For the dashboard link I agree that it's an issue.  I think I'm going to address this by making the dashboard link provided in the `Client` repr configurable.

If there is any other content you think would be useful please don't hesitate to speak up.  I would really value your continued engagement on this.

**Comment by mrocklin** [comment]
I've now resolved the dashboard link as well.  Closing!
